version: "3.9"

services:
  webapp:
    image: registry.digitalocean.com/lights-on-container-registry/web-app:latest
    container_name: webapp
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      AllowedHosts: "*"
      AzureAdB2C__Instance: "https://lightsinua.b2clogin.com"
      AzureAdB2C__ClientId: "c6e03604-f862-4a53-9a75-7eb0a5bfd5b4"
      AzureAdB2C__CallbackPath: "/signin-oidc"
      AzureAdB2C__Domain: "lightsinua.onmicrosoft.com"
      AzureAdB2C__SignedOutCallbackPath: "/signout/B2C_1_susi"
      AzureAdB2C__SignUpSignInPolicyId: "b2c_1_susi"
      AzureAdB2C__ResetPasswordPolicyId: "b2c_1_reset"
      AzureAdB2C__EditProfilePolicyId: "b2c_1_edit_profile"
      Logging__LogLevel__Default: "Information"
      Logging__LogLevel__Microsoft_AspNetCore: "Warning"
      ApiConfigurations__Url: "https://lgenera.com/api"
      SyncfusionLicenseKey: "MjY2OTQxNUAzMjMyMmUzMDJlMzBGcWVZeVFlOEpVOFVJYXY4RjFtelF6UDdTcWN2Q1RXWDVUbWxUSVU5eTBVPQ=="
    ports:
      - "8080:8080"

  webapi:
    image: registry.digitalocean.com/lights-on-container-registry/web-api:latest
    container_name: webapi
    restart: unless-stopped
    environment:
      ASPNETCORE_URLS: http://+:5001
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=myDatabase;User Id=sa;Password=Your_password123;"
    ports:
      - "5001:5001"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - webapp

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  certbot-conf:
  certbot-www: